def
  "x"
value
  do
    "hey"
  catch
    "ERROR"

    (err)
    fn  
      std.write err end
    end
  end
end

std.write x end